### PR TITLE
Unit test

### PR DESCRIPTION
**Pull request by yasmensarhan27**
Unit test using collar, quantum lab and Jupiter notebook

Tried %timeit in another file as well

### CODE REVIEW

**Comment by s4il3sh** [comment]
I can't merge it, it says it has conflicts.

**Comment by yasmensarhan27** [comment]
I think you are the once who can access and resolve conflicts

**Comment by s4il3sh** [comment]
the resolve conflict button is not active

**Comment by yasmensarhan27** [comment]
Can you check now

**Comment by s4il3sh** [comment]
not working

**Comment by s4il3sh** [comment]
did you sync the fork and sent me merge request?

**Comment by yasmensarhan27** [comment]
It has no conflicts now

**Pull request merged**
